name: pytest on Hetzner Cloud

on:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]
  workflow_dispatch:



jobs:
  create-runner:
    name: Create Hetzner Cloud runner
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.create-hcloud-runner.outputs.label }}
      server_id: ${{ steps.create-hcloud-runner.outputs.server_id }}
    steps:
      - name: Create runner
        id: create-hcloud-runner
        uses: Cyclenerd/hcloud-github-runner@v1
        with:
          mode: create
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          hcloud_token: ${{ secrets.HETZNER_API_TOKEN }}
          server_type: cx33
          location: nbg1  # Nuremberg, Germany
          image: ubuntu-22.04
  build:
    env:
      INSTALL_EXTS: false
    name: Do the job on the runner
    needs:
      - create-runner
    runs-on: ${{ needs.create-runner.outputs.label }} # run the job on the newly created runner

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install incus via apt
        run: |
          mkdir -p /etc/apt/keyrings/
          curl -fsSL https://pkgs.zabbly.com/key.asc -o /etc/apt/keyrings/zabbly.asc
          
          echo "Enabled: yes" | tee /etc/apt/sources.list.d/zabbly-incus-lts-6.0.sources
          echo "Types: deb" | tee -a /etc/apt/sources.list.d/zabbly-incus-lts-6.0.sources
          echo "URIs: https://pkgs.zabbly.com/incus/lts-6.0" | tee -a /etc/apt/sources.list.d/zabbly-incus-lts-6.0.sources
          echo "Suites: $(. /etc/os-release && echo "${VERSION_CODENAME}")" | tee -a /etc/apt/sources.list.d/zabbly-incus-lts-6.0.sources
          echo "Components: main" | tee -a /etc/apt/sources.list.d/zabbly-incus-lts-6.0.sources
          echo "Architectures: $(dpkg --print-architecture)" | tee -a /etc/apt/sources.list.d/zabbly-incus-lts-6.0.sources
          echo "Signed-By: /etc/apt/keyrings/zabbly.asc" | tee -a /etc/apt/sources.list.d/zabbly-incus-lts-6.0.sources
          
          apt update
          apt install -y incus incus-client python3.10-venv jq
          incus admin init --auto --network-address=[::] --network-port=8443
          incus admin waitready

#      - name: Setup env for testing
#        if: vars.INSTALL_EXTS == 'true'
#        run: |
#          apt update
#          apt install -y ca-certificates curl
#          install -m 0755 -d /etc/apt/keyrings
#          curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
#          chmod a+r /etc/apt/keyrings/docker.asc
#          . /etc/os-release
#          echo "Types: deb" | tee /etc/apt/sources.list.d/docker.sources
#          echo "URIs: https://download.docker.com/linux/ubuntu" | tee -a /etc/apt/sources.list.d/docker.sources
#          echo "Suites: ${UBUNTU_CODENAME:-$VERSION_CODENAME}" | tee -a /etc/apt/sources.list.d/docker.sources
#          echo "Components: stable" | tee -a /etc/apt/sources.list.d/docker.sources
#          echo "Signed-By: /etc/apt/keyrings/docker.asc" | tee -a /etc/apt/sources.list.d/docker.sources
#          apt-get update
#          apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
#
#          apt install -y podman lvm2 thin-provisioning-tools jq
#
#          dd if=/dev/zero of=/var/lib/ceph-osd.img bs=1G count=1
#          losetup -fP /var/lib/ceph-osd.img
#          LOOPDEV=$(losetup -a | awk -F: '/ceph-osd/ {print $1}')
#
#          curl -fsSL -o /usr/local/bin/cephadm https://github.com/ceph/ceph/raw/quincy/src/cephadm/cephadm
#          chmod +x /usr/local/bin/cephadm
#
#          cephadm bootstrap \
#            --mon-ip "$(curl -s http://checkip.amazonaws.com)" \
#            --single-host-defaults \
#            --skip-monitoring-stack \
#            --skip-ssh
#
#          cephadm shell -- ceph -s
#
#          cephadm shell -- ceph-volume lvm create --data "$LOOPDEV"
#
#          cephadm shell -- ceph osd pool create incus 32


      - name: Run tests
        run: |
          set -euo pipefail
          
          python3.10 -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-test.txt
          pytest --cov --cov-branch --cov-report=xml || true

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: SomeBlackMagic/salt-incus-formula


  delete-runner:
    name: Delete Hetzner Cloud runner
    needs:
      - create-runner # required to get output from the create-runner job
      - build # required to wait when the main job is done
    runs-on: ubuntu-latest
    if: ${{ always() }} # required to stop the runner even if the error happened in the previous jobs
    steps:
      - name: Delete runner
        uses: Cyclenerd/hcloud-github-runner@v1
        with:
          mode: delete
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          hcloud_token: ${{ secrets.HETZNER_API_TOKEN }}
          name: ${{ needs.create-runner.outputs.label }}
          server_id: ${{ needs.create-runner.outputs.server_id }}
